"use client";

import { useTrainer } from "@/context/TrainerContext";
import { explainMove, type CoachMood, type CoachPoint } from "@/lib/coach";
import { formatMoveSequence } from "@/lib/chess";
import { CLASS_META, type MoveReview } from "@/lib/review";
import { Button } from "./ui";

interface Props {
  /** The move that led to the position now on the board (null at move 0). */
  move: MoveReview | null;
  /** Whether that move was the looked-up player's. */
  isUser: boolean;
  /** The move that followed it in the game, when there was one. */
  next?: MoveReview | null;
  /** The board is before the game's first move, so there is nothing to explain. */
  atStart: boolean;
  /** Still sweeping the game — this move may not be judged yet. */
  analyzing: boolean;
}

/** The coach's name and face. */
const COACH = "Coach Nova";

const MOOD: Record<CoachMood, { face: string; avatar: string; card: string }> = {
  celebrate: {
    face: "🤩",
    avatar: "from-teal-400 to-emerald-600",
    card: "border-teal-800/60 bg-teal-950/25",
  },
  happy: {
    face: "🙂",
    avatar: "from-emerald-500 to-emerald-700",
    card: "border-emerald-900/50 bg-emerald-950/20",
  },
  neutral: {
    face: "🧐",
    avatar: "from-slate-500 to-slate-700",
    card: "border-slate-800 bg-slate-900/40",
  },
  concerned: {
    face: "😕",
    avatar: "from-amber-500 to-orange-700",
    card: "border-amber-900/50 bg-amber-950/20",
  },
  alarmed: {
    face: "😬",
    avatar: "from-rose-500 to-rose-800",
    card: "border-rose-900/50 bg-rose-950/20",
  },
};

/** "17...Nf6" for a single move, using its own move number. */
function label(move: MoveReview): string {
  return formatMoveSequence(move.fenBefore, [move.san]);
}

/**
 * The coach: a character who talks through every move of the reviewed game and
 * whose suggestions are playable. Any move named in the text is underlined and
 * clickable — clicking it forks a side line off the game so you can see the idea
 * on the board, with the real game always one click behind you.
 *
 * Explanations come from `lib/coach.ts`, which reads the actual position and the
 * engine's own lines. Nothing here is generated by a language model.
 */
export function CoachCard({
  move,
  isUser,
  next = null,
  atStart,
  analyzing,
}: Props) {
  const {
    ply,
    reviewChallenge,
    startChallenge,
    endChallenge,
    playVariation,
    inVariation,
    variationOrigin,
    variationLabel,
    branchSource,
    restoreGame,
  } = useTrainer();

  // The challenge must be checked *before* inVariation: answering commits the
  // move, which forks a branch, and the variation card would otherwise swallow
  // the correct/wrong verdict. It is driven by `reviewChallenge` rather than by
  // `move` so that re-running the sweep (a depth change) can't strand an armed
  // challenge with no card to dismiss it from.
  if (reviewChallenge && (!move || reviewChallenge.index === move.index)) {
    const pv = move?.bestPv ?? [];
    return (
      <ChallengeCard
        playedSan={move?.san ?? null}
        bestSan={reviewChallenge.bestSan}
        canShowLine={pv.length > 0}
        status={reviewChallenge.status}
        lastWrong={reviewChallenge.lastWrong}
        atPuzzle={ply === reviewChallenge.index}
        onRetry={() =>
          startChallenge(reviewChallenge.index, reviewChallenge.bestSan)
        }
        onGiveUp={() =>
          playVariation(reviewChallenge.index, pv, {
            origin: reviewChallenge.index,
            label: reviewChallenge.bestSan,
          })
        }
        onDismiss={endChallenge}
      />
    );
  }

  // A side line the coach didn't open (you struck out on your own) explains
  // nothing in particular, so there's no move to talk about — just the way back.
  const freeExploring = inVariation && variationOrigin == null;

  if (freeExploring || !move) {
    return (
      <div className="rounded-lg border border-slate-800 bg-slate-900/40 p-3">
        {inVariation && (
          <ExploringStrip label={variationLabel} onBack={() => restoreGame()} />
        )}
        <div className="flex items-center gap-2">
          <Avatar mood="neutral" />
          <div className="min-w-0">
            <p className="text-[14px] lg:text-[15px] font-semibold text-slate-200">
              {inVariation
                ? branchSource === "engine"
                  ? "This is the line the engine wanted."
                  : "You're off the game, playing your own line."
                : atStart
                  ? "Starting position"
                  : "This move isn't judged yet."}
            </p>
            <p className="text-[11px] lg:text-[12px] text-slate-500">{COACH}</p>
          </div>
        </div>
        <p className="mt-1.5 text-[12px] lg:text-[13px] leading-relaxed text-slate-400">
          {inVariation
            ? "Keep playing and Stockfish scores every move as you go — watch the eval bar and the green arrow. Your game is untouched underneath."
            : atStart
              ? "Step forward through the game, or jump straight to a mistake below. I'll explain every move as you land on it, and anything I suggest is clickable — it goes straight onto the board."
              : analyzing
                ? "Stockfish hasn't reached this position yet — give it a moment and I'll talk you through it."
                : "I have no verdict for this move. Step to another one, or re-run the review."}
        </p>
      </div>
    );
  }

  const advice = explainMove(move, { isUser, next });
  const meta = CLASS_META[move.classification];
  const mood = MOOD[advice.mood];
  // While the sweep is still working, a move with no best line yet has nothing
  // behind the words — say so rather than explaining a half-formed verdict.
  const pending = analyzing && move.bestSan == null;
  // "Find the move you should have played" only makes sense for a slip of your
  // own; on their move, or on a move that was already best, it's nonsense.
  const fixable =
    isUser &&
    !pending &&
    ["blunder", "mistake", "inaccuracy"].includes(move.classification) &&
    move.bestSan != null &&
    move.bestSan !== move.san;

  return (
    <div className={`rounded-lg border p-3 ${mood.card}`}>
      {inVariation && (
        <ExploringStrip label={variationLabel} onBack={() => restoreGame()} />
      )}

      <div className="flex items-center gap-2">
        <Avatar mood={advice.mood} />
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-1.5">
            <span className="text-[12px] lg:text-[13px] font-semibold text-slate-200">{COACH}</span>
            <span className="text-[11px] lg:text-[12px] text-slate-500">
              on {isUser ? "your" : "their"} move
            </span>
          </div>
          <div className="flex items-center gap-1.5">
            <span
              className={`shrink-0 rounded px-1.5 py-0.5 text-[10px] lg:text-[11px] font-bold uppercase tracking-wide ${meta.bg} ${meta.text}`}
            >
              {meta.glyph} {meta.label}
            </span>
            <span className="font-mono text-[14px] lg:text-[15px] font-semibold text-slate-100">
              {label(move)}
            </span>
          </div>
        </div>
      </div>

      <p className="mt-2 text-[14px] lg:text-[15px] font-semibold leading-snug text-slate-100">
        {pending ? "Still analysing this one…" : advice.headline}
      </p>

      {!pending && advice.points.length > 0 && (
        <ul className="mt-1.5 flex flex-col gap-1">
          {advice.points.map((point, i) => (
            <li
              key={i}
              className="flex gap-1.5 text-[13px] lg:text-[14px] leading-relaxed text-slate-400"
            >
              <span className="shrink-0 text-slate-600">•</span>
              <span>
                <Sentence point={point} origin={move.index} />
              </span>
            </li>
          ))}
        </ul>
      )}

      {!pending && advice.box && (
        <div
          className={`mt-2 rounded-md border px-2.5 py-2 ${
            advice.box.tone === "good"
              ? "border-emerald-900/50 bg-emerald-950/25"
              : "border-slate-700/70 bg-slate-950/40"
          }`}
        >
          <p
            className={`text-[11px] lg:text-[12px] font-semibold uppercase tracking-wide ${
              advice.box.tone === "good" ? "text-emerald-400" : "text-slate-500"
            }`}
          >
            {advice.box.label}
          </p>
          <p className="mt-0.5 text-[13px] lg:text-[14px] leading-relaxed text-slate-300">
            <Sentence point={advice.box.segments} origin={move.index} />
          </p>
        </div>
      )}

      {!pending && advice.takeaway && (
        <p className="mt-2 border-t border-slate-800 pt-2 text-[12px] lg:text-[13px] italic leading-relaxed text-slate-500">
          💡 {advice.takeaway}
        </p>
      )}

      {fixable && (
        <div className="mt-2 flex gap-1.5">
          <Button
            variant="primary"
            onClick={() => startChallenge(move.index, move.bestSan as string)}
            className="flex-1 !py-1.5 text-[13px] lg:text-sm"
            title="Go back to that position and find the move yourself"
          >
            🎯 Let me try
          </Button>
          <Button
            variant="secondary"
            onClick={() =>
              playVariation(move.index, move.bestPv, {
                origin: move.index,
                label: move.bestSan ?? undefined,
              })
            }
            disabled={move.bestPv.length === 0}
            className="flex-1 !py-1.5 text-[13px] lg:text-sm"
            title="Play the engine's line out on the board"
          >
            ▶ Show the line
          </Button>
        </div>
      )}
    </div>
  );
}

/** The coach's face; the expression tracks how the move went. */
function Avatar({ mood }: { mood: CoachMood }) {
  return (
    <span
      className={`relative inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-gradient-to-br text-[16px] lg:text-[17px] text-white shadow-md ring-1 ring-slate-950/60 ${MOOD[mood].avatar}`}
      aria-hidden
    >
      ♞
      <span className="absolute -bottom-0.5 -right-1 text-[13px] lg:text-[14px] leading-none drop-shadow">
        {MOOD[mood].face}
      </span>
    </span>
  );
}

/**
 * A sentence from the coach. Move references render as underlined links that put
 * the suggestion on the board: `playVariation` splices the line onto the game
 * from the half-move it forks at, so "back to the game" always undoes it.
 */
function Sentence({
  point,
  origin,
}: {
  point: CoachPoint;
  /** The reviewed move being discussed, so the card stays on it while exploring. */
  origin: number;
}) {
  const { playVariation } = useTrainer();
  return (
    <>
      {point.map((seg, i) =>
        seg.kind === "text" ? (
          <span key={i}>{seg.text}</span>
        ) : (
          <button
            key={i}
            type="button"
            title={seg.hint}
            // The visible text is just the move, which says nothing about what
            // clicking does — spell out the action for a screen reader.
            aria-label={seg.hint}
            onClick={() =>
              playVariation(seg.fromPly, seg.sans, { origin, label: seg.text })
            }
            className="inline rounded-sm font-mono font-semibold text-emerald-300 underline decoration-emerald-500/70 decoration-dotted underline-offset-2 transition hover:bg-emerald-500/10 hover:text-emerald-200 hover:decoration-emerald-300 hover:decoration-solid focus-visible:outline focus-visible:outline-1 focus-visible:outline-emerald-400"
          >
            {seg.text}
          </button>
        ),
      )}
    </>
  );
}

/** Banner shown while a side line stands in for part of the game. */
function ExploringStrip({
  label: name,
  onBack,
}: {
  label: string | null;
  onBack: () => void;
}) {
  return (
    <div className="mb-2 flex items-center gap-2 rounded-md border border-sky-800/70 bg-sky-950/40 px-2 py-1.5">
      <span className="min-w-0 flex-1 truncate text-[12px] lg:text-[13px] text-sky-200">
        Exploring{" "}
        {name ? <span className="font-mono font-semibold">{name}</span> : "a side line"}{" "}
        — your game is untouched.
      </span>
      <button
        type="button"
        onClick={onBack}
        className="shrink-0 rounded px-1.5 py-0.5 text-[12px] lg:text-[13px] font-medium text-sky-300 transition hover:bg-sky-900/60 hover:text-sky-100"
      >
        ← Back to the game
      </button>
    </div>
  );
}

/**
 * "Now you try". Your answer lands on the board whether it's right or wrong, so
 * this card also owns the way back: retry re-parks the puzzle, and dismissing
 * puts the real game back.
 */
function ChallengeCard({
  playedSan,
  bestSan,
  canShowLine,
  status,
  lastWrong,
  atPuzzle,
  onRetry,
  onGiveUp,
  onDismiss,
}: {
  /** What was played in the game — null if the sweep has no verdict for it. */
  playedSan: string | null;
  bestSan: string;
  /** Whether there is an engine line to play out. */
  canShowLine: boolean;
  status: "waiting" | "correct" | "wrong";
  lastWrong: string | null;
  /** Whether the board is still on the puzzle position. */
  atPuzzle: boolean;
  onRetry: () => void;
  onGiveUp: () => void;
  onDismiss: () => void;
}) {
  const dismiss = (
    <Button variant="ghost" onClick={onDismiss} className="!py-1.5 text-[13px] lg:text-sm">
      ✕ Done
    </Button>
  );

  return (
    <div className="rounded-lg border border-emerald-800/60 bg-emerald-950/25 p-3">
      <div className="flex items-center gap-2">
        <Avatar mood={status === "correct" ? "celebrate" : "neutral"} />
        <div>
          <p className="text-[11px] lg:text-[12px] font-semibold uppercase tracking-wide text-emerald-400">
            Your turn
          </p>
          <p className="text-[11px] lg:text-[12px] text-slate-500">{COACH}</p>
        </div>
      </div>
      <p className="mt-1.5 text-[14px] lg:text-[15px] font-semibold leading-snug text-slate-100">
        {playedSan
          ? `You played ${playedSan} here.`
          : "This is the position."}{" "}
        Find the move you should have played.
      </p>

      {status === "correct" ? (
        <>
          <p className="mt-2 rounded-md bg-emerald-600/20 px-2.5 py-2 text-[13px] lg:text-[14px] font-semibold text-emerald-200">
            ✓ That&apos;s it — {bestSan} is the move.
          </p>
          <p className="mt-1 text-[12px] lg:text-[13px] leading-relaxed text-slate-400">
            It&apos;s on the board — play on from here to see how it goes, or
            watch the engine&apos;s line.
          </p>
          <div className="mt-2 flex gap-1.5">
            <Button
              variant="primary"
              onClick={onGiveUp}
              disabled={!canShowLine}
              className="flex-1 !py-1.5 text-[13px] lg:text-sm"
            >
              ▶ See the follow-up
            </Button>
            {dismiss}
          </div>
        </>
      ) : status === "wrong" ? (
        <>
          <p className="mt-2 rounded-md bg-rose-600/15 px-2.5 py-2 text-[13px] lg:text-[14px] text-rose-200">
            {lastWrong === playedSan
              ? `${lastWrong} is the move you actually played — there's a better one.`
              : `${lastWrong} isn't it.`}{" "}
            Look for the most forcing option — check every capture and check
            first. It&apos;s on the board with the engine live, so you can see
            what it gives up.
          </p>
          <div className="mt-2 flex gap-1.5">
            <Button
              variant="primary"
              onClick={onRetry}
              className="flex-1 !py-1.5 text-[13px] lg:text-sm"
            >
              ↺ Try again
            </Button>
            <Button
              variant="secondary"
              onClick={onGiveUp}
              className="!py-1.5 text-[13px] lg:text-sm"
            >
              Show me
            </Button>
            {dismiss}
          </div>
        </>
      ) : !atPuzzle ? (
        <>
          <p className="mt-1 text-[12px] lg:text-[13px] leading-relaxed text-slate-400">
            You&apos;ve stepped away from the puzzle position.
          </p>
          <div className="mt-2 flex gap-1.5">
            <Button
              variant="primary"
              onClick={onRetry}
              className="flex-1 !py-1.5 text-[13px] lg:text-sm"
            >
              ← Back to the puzzle
            </Button>
            {dismiss}
          </div>
        </>
      ) : (
        <>
          <p className="mt-1 text-[12px] lg:text-[13px] leading-relaxed text-slate-400">
            Play it on the board — right or wrong, your move lands, and your game
            is one click away.
          </p>
          <div className="mt-2 flex gap-1.5">
            <Button
              variant="secondary"
              onClick={onGiveUp}
              className="flex-1 !py-1.5 text-[13px] lg:text-sm"
            >
              Show me
            </Button>
            {dismiss}
          </div>
        </>
      )}
    </div>
  );
}
